### ISSUE TITLE
Github action date format

### ISSUE THREAD

**Issue by joostschouppe** [osmbe/traffic-sign-project#16]
The action asks for 'Last processed data in YY-MM-DD format', but the field seems to be expecting  DD-MM-YY format instead

**Comment by ivandiaz-tomtom** [comment]
`extract_new_signs` function converts `datum_plaatsing` to dd/mm/yy.

```
  feature_df['date'] = pd.to_datetime(feature_df['datum_plaatsing'], errors = 'coerce', format='%d/%m/%Y')
```
testing it now to have one single parsing method.

**Comment by ivandiaz-tomtom** [comment]
Ok, so now I recall this usage. The idea of the Last processed date` was only for a manual run. The main idea of the GitHub actions was to have them scheduled monthly and use the default by fetching the first day of the previous month.

**Comment by ivandiaz-tomtom** [comment]
Updated in my fork https://github.com/ivandiaz-tomtom/traffic-sign-project/commit/e078833d3016c9611d2d2176ea8464f2e62ee15f

**Comment by joostschouppe** [comment]
Fixed above
